### ISSUE TITLE
Gaya Penulisan Kode

### ISSUE THREAD

**Issue by jefrydco** [Rakhmadi/Submision-Aplikasi-Satu-Halaman-Vuejs#1]
Hi Mas Rakhmadi, terima kasih sudah mengirimkan kode belajar Vue.js Fundamental, saya sangat mengapresiasi kerja keras Mas Rakhmadi. Saya ada beberapa saran kecil Mas terkait gaya penulisan kode:

1. Spasi Antar Operator JavaScript
Saya mengambil contoh kode pada berkas `index.html` baris ke 133 berikut:

https://github.com/Rakhmadi/Submision-Aplikasi-Satu-Halaman-Vuejs/blob/dea986be584db9ee09b146f26c19194f5fd38507/index.html#L133

Saya sarankan Mas untuk menambahkan spasi antara `=` dengan `this.hu` dan `false`.
Hal ini akan sangat membantu untuk meningkatkan keterbacaan kode.

Referensi: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Code_guidelines/JavaScript#Use_expanded_syntax

2. Menggunakan _Camel Case_ untuk Penulisan Nama Fungsi
Saya mengambil contoh kode pada berkas `index.html` baris ke 138 berikut:

https://github.com/Rakhmadi/Submision-Aplikasi-Satu-Halaman-Vuejs/blob/dea986be584db9ee09b146f26c19194f5fd38507/index.html#L138

Jika nama fungsi terdiri dari 2 kata, saya sarankan Mas untuk menggunakan penamaan _camel case_. Penggunaan _camel case_ pada JavaScript seperti menjadi aturan yang tidak tertulis pada kalangan pengembang perangkat lunak Mas. Jadi ada baiknya kita juga mengiktinya.

Referensi: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Code_guidelines/JavaScript#Variable_naming

---

Walaupun terlihat sepeleh, namun menurut saya akan sangat berguna Mas untuk kedepannya nanti. Apalagi jika sudah bekerja di dalam tim, gaya penulisan kode yg seragam akan sangat membantu anggota tim lain untuk beradaptasi. Bahkan kalau bisa kode tersebut seolah olah nampak ditulis oleh satu orang saja karena gaya penulisannya seragam.

Lebih lanjut Mas dapat membaca pada tautan berikut, [Mozilla Developer Network - JavaScript guidelines](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Code_guidelines/JavaScript)

Semangat Mas! 😄

**Comment by Rakhmadi** [comment]
Terima Kasih atas Sarannya 👍
